apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: api-style-guide
  title: API Style Guide
  description: Guia oficial de estilo para APIs
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: documentation
  lifecycle: production
  owner: arquitetura-integracao
